@BASE_URL = http://localhost:3000

### GET Welcome
GET {{BASE_URL}}

### GET Users
GET {{BASE_URL}}/users

### GET User by id
GET {{BASE_URL}}/users/333

### PATCH User
PATCH {{BASE_URL}}/users/2
Content-Type: application/json

{
    "name": "JaJa"
}

### DELETE User
DELETE {{BASE_URL}}/users/4